import template1 from "../assets/templatesAsImage/1.svg"
import template2 from "../assets/templatesAsImage/2.svg"
import template3 from "../assets/templatesAsImage/3.svg"
import template4 from "../assets/templatesAsImage/4.svg"
import template5 from "../assets/templatesAsImage/5.svg"
import template6 from "../assets/templatesAsImage/6.svg"
import template7 from "../assets/templatesAsImage/7.svg"
import template8 from "../assets/templatesAsImage/8.svg"
import template9 from "../assets/templatesAsImage/9.svg"
import template10 from "../assets/templatesAsImage/10.svg"
import template11 from "../assets/templatesAsImage/11.svg"
import template12 from "../assets/templatesAsImage/12.svg"
import template13 from "../assets/templatesAsImage/13.svg"
import template14 from "../assets/templatesAsImage/14.svg"
import template15 from "../assets/templatesAsImage/15.svg"
import template16 from "../assets/templatesAsImage/16.svg"
import template17 from "../assets/templatesAsImage/17.svg"
import template18 from "../assets/templatesAsImage/18.svg"
import template19 from "../assets/templatesAsImage/19.svg"
import template20 from "../assets/templatesAsImage/20.svg"
import template21 from "../assets/templatesAsImage/21.svg"
import template22 from "../assets/templatesAsImage/22.svg"
import template23 from "../assets/templatesAsImage/23.svg"
import template24 from "../assets/templatesAsImage/24.svg"
import template25 from "../assets/templatesAsImage/25.svg"
import template26 from "../assets/templatesAsImage/26.svg"
import template27 from "../assets/templatesAsImage/27.svg"
import template28 from "../assets/templatesAsImage/28.svg"
import template29 from "../assets/templatesAsImage/29.svg"
import template30 from "../assets/templatesAsImage/30.svg"
import template31 from "../assets/templatesAsImage/31.svg"
import template32 from "../assets/templatesAsImage/32.svg"
import template33 from "../assets/templatesAsImage/33.svg"
import template34 from "../assets/templatesAsImage/34.svg"
import template35 from "../assets/templatesAsImage/35.svg"
import template36 from "../assets/templatesAsImage/36.svg"

const  templateImageArray = [[template1, 1], [template2, 2], [template3, 3], [template4, 4], [template5, 5], [template6, 6], [template7, 7], [template8, 8], [template9, 9], [template10, 10], [template11, 11], [template12, 12], [template13, 13], [template14, 14], [template15, 15], [template16, 16], [template17, 17], [template18, 18], [template19, 19], [template20, 20], [template21, 21], [template22, 22], [template23, 23], [template24, 24], [template25, 25], [template26, 26], [template27, 27], [template28, 28], [template29, 29], [template30, 30], [template31, 31], [template32, 32], [template33, 33], [template34, 34], [template35, 35], [template36, 36]]

export default templateImageArray;